#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : tablib
Version  : 0.11.2
Release  : 13
URL      : https://pypi.python.org/packages/source/t/tablib/tablib-0.11.2.tar.gz
Source0  : https://pypi.python.org/packages/source/t/tablib/tablib-0.11.2.tar.gz
Summary  : Format agnostic tabular data library (XLS, JSON, YAML, CSV)
Group    : Development/Tools
License  : Apache-2.0 BSD-4-Clause BSD-4-Clause-UC MIT
Requires: tablib-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
Tablib: format-agnostic tabular dataset library
===============================================

%package python
Summary: python components for the tablib package.
Group: Default

%description python
python components for the tablib package.


%prep
%setup -q -n tablib-0.11.2

%build
python2 setup.py build -b py2
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
python test_tablib.py
%install
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
