#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : tablib
Version  : 0.11.5
Release  : 18
URL      : https://pypi.python.org/packages/d6/b8/f606258ec113a2d244c0c7254c57d1dd0f5d2ba090c7d26216c4a354243b/tablib-0.11.5.tar.gz
Source0  : https://pypi.python.org/packages/d6/b8/f606258ec113a2d244c0c7254c57d1dd0f5d2ba090c7d26216c4a354243b/tablib-0.11.5.tar.gz
Summary  : Format agnostic tabular data library (XLS, JSON, YAML, CSV)
Group    : Development/Tools
License  : MIT
Requires: tablib-python
Requires: unicodecsv
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
Tablib: format-agnostic tabular dataset library
===============================================

%package python
Summary: python components for the tablib package.
Group: Default

%description python
python components for the tablib package.


%prep
%setup -q -n tablib-0.11.5

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1498667860
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1498667860
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python2*/*
/usr/lib/python3*/*
