#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : tablib
Version  : 0.11.4
Release  : 16
URL      : https://pypi.python.org/packages/99/e2/eb6c7b83bd5d2dc7148ca9d1b4ebfeb134c8fc03af83cddc1e65f8cd216b/tablib-0.11.4.tar.gz
Source0  : https://pypi.python.org/packages/99/e2/eb6c7b83bd5d2dc7148ca9d1b4ebfeb134c8fc03af83cddc1e65f8cd216b/tablib-0.11.4.tar.gz
Summary  : Format agnostic tabular data library (XLS, JSON, YAML, CSV)
Group    : Development/Tools
License  : Apache-2.0 BSD-4-Clause BSD-4-Clause-UC MIT
Requires: tablib-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
Tablib: format-agnostic tabular dataset library
===============================================

%package python
Summary: python components for the tablib package.
Group: Default

%description python
python components for the tablib package.


%prep
%setup -q -n tablib-0.11.4

%build
export LANG=C
export SOURCE_DATE_EPOCH=1487703519
python2 setup.py build -b py2
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
python test_tablib.py
%install
export SOURCE_DATE_EPOCH=1487703519
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
